<?php

use App\Country;
use App\Continent;
use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        $data = [
            'AF' => [
                'name'      => 'Africa',
                'code'      => 'AF',
                'countries' => [
                    [
                        'name'              => 'Angola',
                        'code_iso_a2'       => 'AO',
                        'code_iso_a3'       => 'AGO',
                        'code_iso_numberic' => '024',
                    ],
                    [
                        'name'              => 'Burkina Faso',
                        'code_iso_a2'       => 'BF',
                        'code_iso_a3'       => 'BFA',
                        'code_iso_numberic' => '854',
                    ],
                    [
                        'name'              => 'Burundi',
                        'code_iso_a2'       => 'BI',
                        'code_iso_a3'       => 'BDI',
                        'code_iso_numberic' => '108',
                    ],
                    [
                        'name'              => 'Benin',
                        'code_iso_a2'       => 'BJ',
                        'code_iso_a3'       => 'BEN',
                        'code_iso_numberic' => '204',
                    ],
                    [
                        'name'              => 'Botswana',
                        'code_iso_a2'       => 'BW',
                        'code_iso_a3'       => 'BWA',
                        'code_iso_numberic' => '072',
                    ],
                    [
                        'name'              => 'Congo (Kinshasa)',
                        'code_iso_a2'       => 'CD',
                        'code_iso_a3'       => 'COD',
                        'code_iso_numberic' => '180',
                    ],
                    [
                        'name'              => 'Central African Republic',
                        'code_iso_a2'       => 'CF',
                        'code_iso_a3'       => 'CAF',
                        'code_iso_numberic' => '140',
                    ],
                    [
                        'name'              => 'Congo (Brazzaville)',
                        'code_iso_a2'       => 'CG',
                        'code_iso_a3'       => 'COG',
                        'code_iso_numberic' => '178',
                    ],
                    [
                        'name'              => 'Côte d\'Ivoire',
                        'code_iso_a2'       => 'CI',
                        'code_iso_a3'       => 'CIV',
                        'code_iso_numberic' => '384',
                    ],
                    [
                        'name'              => 'Cameroon',
                        'code_iso_a2'       => 'CM',
                        'code_iso_a3'       => 'CMR',
                        'code_iso_numberic' => '120',
                    ],
                    [
                        'name'              => 'Cape Verde',
                        'code_iso_a2'       => 'CV',
                        'code_iso_a3'       => 'CPV',
                        'code_iso_numberic' => '132',
                    ],
                    [
                        'name'              => 'Djibouti',
                        'code_iso_a2'       => 'DJ',
                        'code_iso_a3'       => 'DJI',
                        'code_iso_numberic' => '262',
                    ],
                    [
                        'name'              => 'Algeria',
                        'code_iso_a2'       => 'DZ',
                        'code_iso_a3'       => 'DZA',
                        'code_iso_numberic' => '012',
                    ],
                    [
                        'name'              => 'Egypt',
                        'code_iso_a2'       => 'EG',
                        'code_iso_a3'       => 'EGY',
                        'code_iso_numberic' => '818',
                    ],
                    [
                        'name'              => 'Western Sahara',
                        'code_iso_a2'       => 'EH',
                        'code_iso_a3'       => 'ESH',
                        'code_iso_numberic' => '732',
                    ],
                    [
                        'name'              => 'Eritrea',
                        'code_iso_a2'       => 'ER',
                        'code_iso_a3'       => 'ERI',
                        'code_iso_numberic' => '232',
                    ],
                    [
                        'name'              => 'Ethiopia',
                        'code_iso_a2'       => 'ET',
                        'code_iso_a3'       => 'ETH',
                        'code_iso_numberic' => '231',
                    ],
                    [
                        'name'              => 'Gabon',
                        'code_iso_a2'       => 'GA',
                        'code_iso_a3'       => 'GAB',
                        'code_iso_numberic' => '266',
                    ],
                    [
                        'name'              => 'Ghana',
                        'code_iso_a2'       => 'GH',
                        'code_iso_a3'       => 'GHA',
                        'code_iso_numberic' => '288',
                    ],
                    [
                        'name'              => 'Gambia',
                        'code_iso_a2'       => 'GM',
                        'code_iso_a3'       => 'GMB',
                        'code_iso_numberic' => '270',
                    ],
                    [
                        'name'              => 'Guinea',
                        'code_iso_a2'       => 'GN',
                        'code_iso_a3'       => 'GIN',
                        'code_iso_numberic' => '324',
                    ],
                    [
                        'name'              => 'Equatorial Guinea',
                        'code_iso_a2'       => 'GQ',
                        'code_iso_a3'       => 'GNQ',
                        'code_iso_numberic' => '226',
                    ],
                    [
                        'name'              => 'Guinea-Bissau',
                        'code_iso_a2'       => 'GW',
                        'code_iso_a3'       => 'GNB',
                        'code_iso_numberic' => '624',
                    ],
                    [
                        'name'              => 'Kenya',
                        'code_iso_a2'       => 'KE',
                        'code_iso_a3'       => 'KEN',
                        'code_iso_numberic' => '404',
                    ],
                    [
                        'name'              => 'Comoros',
                        'code_iso_a2'       => 'KM',
                        'code_iso_a3'       => 'COM',
                        'code_iso_numberic' => '174',
                    ],
                    [
                        'name'              => 'Liberia',
                        'code_iso_a2'       => 'LR',
                        'code_iso_a3'       => 'LBR',
                        'code_iso_numberic' => '430',
                    ],
                    [
                        'name'              => 'Lesotho',
                        'code_iso_a2'       => 'LS',
                        'code_iso_a3'       => 'LSO',
                        'code_iso_numberic' => '426',
                    ],
                    [
                        'name'              => 'Libya',
                        'code_iso_a2'       => 'LY',
                        'code_iso_a3'       => 'LBY',
                        'code_iso_numberic' => '434',
                    ],
                    [
                        'name'              => 'Morocco',
                        'code_iso_a2'       => 'MA',
                        'code_iso_a3'       => 'MAR',
                        'code_iso_numberic' => '504',
                    ],
                    [
                        'name'              => 'Madagascar',
                        'code_iso_a2'       => 'MG',
                        'code_iso_a3'       => 'MDG',
                        'code_iso_numberic' => '450',
                    ],
                    [
                        'name'              => 'Mali',
                        'code_iso_a2'       => 'ML',
                        'code_iso_a3'       => 'MLI',
                        'code_iso_numberic' => '466',
                    ],
                    [
                        'name'              => 'Mauritania',
                        'code_iso_a2'       => 'MR',
                        'code_iso_a3'       => 'MRT',
                        'code_iso_numberic' => '478',
                    ],
                    [
                        'name'              => 'Mauritius',
                        'code_iso_a2'       => 'MU',
                        'code_iso_a3'       => 'MUS',
                        'code_iso_numberic' => '480',
                    ],
                    [
                        'name'              => 'Malawi',
                        'code_iso_a2'       => 'MW',
                        'code_iso_a3'       => 'MWI',
                        'code_iso_numberic' => '454',
                    ],
                    [
                        'name'              => 'Mozambique',
                        'code_iso_a2'       => 'MZ',
                        'code_iso_a3'       => 'MOZ',
                        'code_iso_numberic' => '508',
                    ],
                    [
                        'name'              => 'Namibia',
                        'code_iso_a2'       => 'NA',
                        'code_iso_a3'       => 'NAM',
                        'code_iso_numberic' => '516',
                    ],
                    [
                        'name'              => 'Niger',
                        'code_iso_a2'       => 'NE',
                        'code_iso_a3'       => 'NER',
                        'code_iso_numberic' => '562',
                    ],
                    [
                        'name'              => 'Nigeria',
                        'code_iso_a2'       => 'NG',
                        'code_iso_a3'       => 'NGA',
                        'code_iso_numberic' => '566',
                    ],
                    [
                        'name'              => 'Reunion',
                        'code_iso_a2'       => 'RE',
                        'code_iso_a3'       => 'REU',
                        'code_iso_numberic' => '638',
                    ],
                    [
                        'name'              => 'Rwanda',
                        'code_iso_a2'       => 'RW',
                        'code_iso_a3'       => 'RWA',
                        'code_iso_numberic' => '646',
                    ],
                    [
                        'name'              => 'Seychelles',
                        'code_iso_a2'       => 'SC',
                        'code_iso_a3'       => 'SYC',
                        'code_iso_numberic' => '690',
                    ],
                    [
                        'name'              => 'Sudan',
                        'code_iso_a2'       => 'SD',
                        'code_iso_a3'       => 'SDN',
                        'code_iso_numberic' => '736',
                    ],
                    [
                        'name'              => 'Saint Helena',
                        'code_iso_a2'       => 'SH',
                        'code_iso_a3'       => 'SHN',
                        'code_iso_numberic' => '654',
                    ],
                    [
                        'name'              => 'Sierra Leone',
                        'code_iso_a2'       => 'SL',
                        'code_iso_a3'       => 'SLE',
                        'code_iso_numberic' => '694',
                    ],
                    [
                        'name'              => 'Senegal',
                        'code_iso_a2'       => 'SN',
                        'code_iso_a3'       => 'SEN',
                        'code_iso_numberic' => '686',
                    ],
                    [
                        'name'              => 'Somalia',
                        'code_iso_a2'       => 'SO',
                        'code_iso_a3'       => 'SOM',
                        'code_iso_numberic' => '706',
                    ],
                    [
                        'name'              => 'Sao Tome and Principe',
                        'code_iso_a2'       => 'ST',
                        'code_iso_a3'       => 'STP',
                        'code_iso_numberic' => '678',
                    ],
                    [
                        'name'              => 'Swaziland',
                        'code_iso_a2'       => 'SZ',
                        'code_iso_a3'       => 'SWZ',
                        'code_iso_numberic' => '748',
                    ],
                    [
                        'name'              => 'Chad',
                        'code_iso_a2'       => 'TD',
                        'code_iso_a3'       => 'TCD',
                        'code_iso_numberic' => '148',
                    ],
                    [
                        'name'              => 'Togo',
                        'code_iso_a2'       => 'TG',
                        'code_iso_a3'       => 'TGO',
                        'code_iso_numberic' => '768',
                    ],
                    [
                        'name'              => 'Tunisia',
                        'code_iso_a2'       => 'TN',
                        'code_iso_a3'       => 'TUN',
                        'code_iso_numberic' => '788',
                    ],
                    [
                        'name'              => 'Tanzania',
                        'code_iso_a2'       => 'TZ',
                        'code_iso_a3'       => 'TZA',
                        'code_iso_numberic' => '834',
                    ],
                    [
                        'name'              => 'Uganda',
                        'code_iso_a2'       => 'UG',
                        'code_iso_a3'       => 'UGA',
                        'code_iso_numberic' => '800',
                    ],
                    [
                        'name'              => 'Mayotte',
                        'code_iso_a2'       => 'YT',
                        'code_iso_a3'       => 'MYT',
                        'code_iso_numberic' => '175',
                    ],
                    [
                        'name'              => 'South Africa',
                        'code_iso_a2'       => 'ZA',
                        'code_iso_a3'       => 'ZAF',
                        'code_iso_numberic' => '710',
                    ],
                    [
                        'name'              => 'Zambia',
                        'code_iso_a2'       => 'ZM',
                        'code_iso_a3'       => 'ZMB',
                        'code_iso_numberic' => '894',
                    ],
                    [
                        'name'              => 'Zimbabwe',
                        'code_iso_a2'       => 'ZW',
                        'code_iso_a3'       => 'ZWE',
                        'code_iso_numberic' => '716',
                    ],
                ],
            ],
            'AN' => [
                'name'      => 'Antarctica',
                'code'      => 'AN',
                'countries' => [
                    [
                        'name'              => 'Antarctica',
                        'code_iso_a2'       => 'AQ',
                        'code_iso_a3'       => 'ATA',
                        'code_iso_numberic' => '010',
                    ],
                    [
                        'name'              => 'Bouvet Island',
                        'code_iso_a2'       => 'BV',
                        'code_iso_a3'       => 'BVT',
                        'code_iso_numberic' => '074',
                    ],
                    [
                        'name'              => 'South Georgia and South Sandwich Islands',
                        'code_iso_a2'       => 'GS',
                        'code_iso_a3'       => 'SGS',
                        'code_iso_numberic' => '239',
                    ],
                    [
                        'name'              => 'Heard and McDonald Islands',
                        'code_iso_a2'       => 'HM',
                        'code_iso_a3'       => 'HMD',
                        'code_iso_numberic' => '334',
                    ],
                    [
                        'name'              => 'French Southern Lands',
                        'code_iso_a2'       => 'TF',
                        'code_iso_a3'       => 'ATF',
                        'code_iso_numberic' => '260',
                    ],
                ],
            ],
            'AS' => [
                'name'      => 'Asia',
                'code'      => 'AS',
                'countries' => [
                    [
                        'name'              => 'United Arab Emirates',
                        'code_iso_a2'       => 'AE',
                        'code_iso_a3'       => 'ARE',
                        'code_iso_numberic' => '784',
                    ],
                    [
                        'name'              => 'Afghanistan',
                        'code_iso_a2'       => 'AF',
                        'code_iso_a3'       => 'AFG',
                        'code_iso_numberic' => '004',
                    ],
                    [
                        'name'              => 'Armenia',
                        'code_iso_a2'       => 'AM',
                        'code_iso_a3'       => 'ARM',
                        'code_iso_numberic' => '051',
                    ],
                    [
                        'name'              => 'Azerbaijan',
                        'code_iso_a2'       => 'AZ',
                        'code_iso_a3'       => 'AZE',
                        'code_iso_numberic' => '031',
                    ],
                    [
                        'name'              => 'Bangladesh',
                        'code_iso_a2'       => 'BD',
                        'code_iso_a3'       => 'BGD',
                        'code_iso_numberic' => '050',
                    ],
                    [
                        'name'              => 'Bahrain',
                        'code_iso_a2'       => 'BH',
                        'code_iso_a3'       => 'BHR',
                        'code_iso_numberic' => '048',
                    ],
                    [
                        'name'              => 'Brunei Darussalam',
                        'code_iso_a2'       => 'BN',
                        'code_iso_a3'       => 'BRN',
                        'code_iso_numberic' => '096',
                    ],
                    [
                        'name'              => 'Bhutan',
                        'code_iso_a2'       => 'BT',
                        'code_iso_a3'       => 'BTN',
                        'code_iso_numberic' => '064',
                    ],
                    [
                        'name'              => 'Cocos (Keeling) Islands',
                        'code_iso_a2'       => 'CC',
                        'code_iso_a3'       => 'CCK',
                        'code_iso_numberic' => '166',
                    ],
                    [
                        'name'              => 'China',
                        'code_iso_a2'       => 'CN',
                        'code_iso_a3'       => 'CHN',
                        'code_iso_numberic' => '156',
                    ],
                    [
                        'name'              => 'Christmas Island',
                        'code_iso_a2'       => 'CX',
                        'code_iso_a3'       => 'CXR',
                        'code_iso_numberic' => '162',
                    ],
                    [
                        'name'              => 'Cyprus',
                        'code_iso_a2'       => 'CY',
                        'code_iso_a3'       => 'CYP',
                        'code_iso_numberic' => '196',
                    ],
                    [
                        'name'              => 'Georgia',
                        'code_iso_a2'       => 'GE',
                        'code_iso_a3'       => 'GEO',
                        'code_iso_numberic' => '268',
                    ],
                    [
                        'name'              => 'Hong Kong',
                        'code_iso_a2'       => 'HK',
                        'code_iso_a3'       => 'HKG',
                        'code_iso_numberic' => '344',
                    ],
                    [
                        'name'              => 'Indonesia',
                        'code_iso_a2'       => 'ID',
                        'code_iso_a3'       => 'IDN',
                        'code_iso_numberic' => '360',
                    ],
                    [
                        'name'              => 'Israel',
                        'code_iso_a2'       => 'IL',
                        'code_iso_a3'       => 'ISR',
                        'code_iso_numberic' => '376',
                    ],
                    [
                        'name'              => 'India',
                        'code_iso_a2'       => 'IN',
                        'code_iso_a3'       => 'IND',
                        'code_iso_numberic' => '356',
                    ],
                    [
                        'name'              => 'British Indian Ocean Territory',
                        'code_iso_a2'       => 'IO',
                        'code_iso_a3'       => 'IOT',
                        'code_iso_numberic' => '086',
                    ],
                    [
                        'name'              => 'Iraq',
                        'code_iso_a2'       => 'IQ',
                        'code_iso_a3'       => 'IRQ',
                        'code_iso_numberic' => '368',
                    ],
                    [
                        'name'              => 'Iran',
                        'code_iso_a2'       => 'IR',
                        'code_iso_a3'       => 'IRN',
                        'code_iso_numberic' => '364',
                    ],
                    [
                        'name'              => 'Jordan',
                        'code_iso_a2'       => 'JO',
                        'code_iso_a3'       => 'JOR',
                        'code_iso_numberic' => '400',
                    ],
                    [
                        'name'              => 'Japan',
                        'code_iso_a2'       => 'JP',
                        'code_iso_a3'       => 'JPN',
                        'code_iso_numberic' => '392',
                    ],
                    [
                        'name'              => 'Kyrgyzstan',
                        'code_iso_a2'       => 'KG',
                        'code_iso_a3'       => 'KGZ',
                        'code_iso_numberic' => '417',
                    ],
                    [
                        'name'              => 'Cambodia',
                        'code_iso_a2'       => 'KH',
                        'code_iso_a3'       => 'KHM',
                        'code_iso_numberic' => '116',
                    ],
                    [
                        'name'              => 'Korea, North',
                        'code_iso_a2'       => 'KP',
                        'code_iso_a3'       => 'PRK',
                        'code_iso_numberic' => '408',
                    ],
                    [
                        'name'              => 'Korea, South',
                        'code_iso_a2'       => 'KR',
                        'code_iso_a3'       => 'KOR',
                        'code_iso_numberic' => '410',
                    ],
                    [
                        'name'              => 'Kuwait',
                        'code_iso_a2'       => 'KW',
                        'code_iso_a3'       => 'KWT',
                        'code_iso_numberic' => '414',
                    ],
                    [
                        'name'              => 'Kazakhstan',
                        'code_iso_a2'       => 'KZ',
                        'code_iso_a3'       => 'KAZ',
                        'code_iso_numberic' => '398',
                    ],
                    [
                        'name'              => 'Laos',
                        'code_iso_a2'       => 'LA',
                        'code_iso_a3'       => 'LAO',
                        'code_iso_numberic' => '418',
                    ],
                    [
                        'name'              => 'Lebanon',
                        'code_iso_a2'       => 'LB',
                        'code_iso_a3'       => 'LBN',
                        'code_iso_numberic' => '422',
                    ],
                    [
                        'name'              => 'Sri Lanka',
                        'code_iso_a2'       => 'LK',
                        'code_iso_a3'       => 'LKA',
                        'code_iso_numberic' => '144',
                    ],
                    [
                        'name'              => 'Myanmar',
                        'code_iso_a2'       => 'MM',
                        'code_iso_a3'       => 'MMR',
                        'code_iso_numberic' => '104',
                    ],
                    [
                        'name'              => 'Mongolia',
                        'code_iso_a2'       => 'MN',
                        'code_iso_a3'       => 'MNG',
                        'code_iso_numberic' => '496',
                    ],
                    [
                        'name'              => 'Macau',
                        'code_iso_a2'       => 'MO',
                        'code_iso_a3'       => 'MAC',
                        'code_iso_numberic' => '446',
                    ],
                    [
                        'name'              => 'Maldives',
                        'code_iso_a2'       => 'MV',
                        'code_iso_a3'       => 'MDV',
                        'code_iso_numberic' => '462',
                    ],
                    [
                        'name'              => 'Malaysia',
                        'code_iso_a2'       => 'MY',
                        'code_iso_a3'       => 'MYS',
                        'code_iso_numberic' => '458',
                    ],
                    [
                        'name'              => 'Nepal',
                        'code_iso_a2'       => 'NP',
                        'code_iso_a3'       => 'NPL',
                        'code_iso_numberic' => '524',
                    ],
                    [
                        'name'              => 'Oman',
                        'code_iso_a2'       => 'OM',
                        'code_iso_a3'       => 'OMN',
                        'code_iso_numberic' => '512',
                    ],
                    [
                        'name'              => 'Philippines',
                        'code_iso_a2'       => 'PH',
                        'code_iso_a3'       => 'PHL',
                        'code_iso_numberic' => '608',
                    ],
                    [
                        'name'              => 'Pakistan',
                        'code_iso_a2'       => 'PK',
                        'code_iso_a3'       => 'PAK',
                        'code_iso_numberic' => '586',
                    ],
                    [
                        'name'              => 'Palestine',
                        'code_iso_a2'       => 'PS',
                        'code_iso_a3'       => 'PSE',
                        'code_iso_numberic' => '275',
                    ],
                    [
                        'name'              => 'Qatar',
                        'code_iso_a2'       => 'QA',
                        'code_iso_a3'       => 'QAT',
                        'code_iso_numberic' => '634',
                    ],
                    [
                        'name'              => 'Saudi Arabia',
                        'code_iso_a2'       => 'SA',
                        'code_iso_a3'       => 'SAU',
                        'code_iso_numberic' => '682',
                    ],
                    [
                        'name'              => 'Singapore',
                        'code_iso_a2'       => 'SG',
                        'code_iso_a3'       => 'SGP',
                        'code_iso_numberic' => '702',
                    ],
                    [
                        'name'              => 'Syria',
                        'code_iso_a2'       => 'SY',
                        'code_iso_a3'       => 'SYR',
                        'code_iso_numberic' => '760',
                    ],
                    [
                        'name'              => 'Thailand',
                        'code_iso_a2'       => 'TH',
                        'code_iso_a3'       => 'THA',
                        'code_iso_numberic' => '764',
                    ],
                    [
                        'name'              => 'Tajikistan',
                        'code_iso_a2'       => 'TJ',
                        'code_iso_a3'       => 'TJK',
                        'code_iso_numberic' => '762',
                    ],
                    [
                        'name'              => 'Timor-Leste',
                        'code_iso_a2'       => 'TL',
                        'code_iso_a3'       => 'TLS',
                        'code_iso_numberic' => '626',
                    ],
                    [
                        'name'              => 'Turkmenistan',
                        'code_iso_a2'       => 'TM',
                        'code_iso_a3'       => 'TKM',
                        'code_iso_numberic' => '795',
                    ],
                    [
                        'name'              => 'Turkey',
                        'code_iso_a2'       => 'TR',
                        'code_iso_a3'       => 'TUR',
                        'code_iso_numberic' => '792',
                    ],
                    [
                        'name'              => 'Taiwan',
                        'code_iso_a2'       => 'TW',
                        'code_iso_a3'       => 'TWN',
                        'code_iso_numberic' => '158',
                    ],
                    [
                        'name'              => 'Uzbekistan',
                        'code_iso_a2'       => 'UZ',
                        'code_iso_a3'       => 'UZB',
                        'code_iso_numberic' => '860',
                    ],
                    [
                        'name'              => 'Vietnam',
                        'code_iso_a2'       => 'VN',
                        'code_iso_a3'       => 'VNM',
                        'code_iso_numberic' => '704',
                    ],
                    [
                        'name'              => 'Yemen',
                        'code_iso_a2'       => 'YE',
                        'code_iso_a3'       => 'YEM',
                        'code_iso_numberic' => '887',
                    ],
                ],
            ],
            'EU' => [
                'name'      => 'Europe',
                'code'      => 'EU',
                'countries' => [
                    [
                        'name'              => 'Andorra',
                        'code_iso_a2'       => 'AD',
                        'code_iso_a3'       => 'AND',
                        'code_iso_numberic' => '020',
                    ],
                    [
                        'name'              => 'Albania',
                        'code_iso_a2'       => 'AL',
                        'code_iso_a3'       => 'ALB',
                        'code_iso_numberic' => '008',
                    ],
                    [
                        'name'              => 'Austria',
                        'code_iso_a2'       => 'AT',
                        'code_iso_a3'       => 'AUT',
                        'code_iso_numberic' => '040',
                    ],
                    [
                        'name'              => 'Åland',
                        'code_iso_a2'       => 'AX',
                        'code_iso_a3'       => 'ALA',
                        'code_iso_numberic' => '248',
                    ],
                    [
                        'name'              => 'Bosnia and Herzegovina',
                        'code_iso_a2'       => 'BA',
                        'code_iso_a3'       => 'BIH',
                        'code_iso_numberic' => '070',
                    ],
                    [
                        'name'              => 'Belgium',
                        'code_iso_a2'       => 'BE',
                        'code_iso_a3'       => 'BEL',
                        'code_iso_numberic' => '056',
                    ],
                    [
                        'name'              => 'Bulgaria',
                        'code_iso_a2'       => 'BG',
                        'code_iso_a3'       => 'BGR',
                        'code_iso_numberic' => '100',
                    ],
                    [
                        'name'              => 'Belarus',
                        'code_iso_a2'       => 'BY',
                        'code_iso_a3'       => 'BLR',
                        'code_iso_numberic' => '112',
                    ],
                    [
                        'name'              => 'Switzerland',
                        'code_iso_a2'       => 'CH',
                        'code_iso_a3'       => 'CHE',
                        'code_iso_numberic' => '756',
                    ],
                    [
                        'name'              => 'Czech Republic',
                        'code_iso_a2'       => 'CZ',
                        'code_iso_a3'       => 'CZE',
                        'code_iso_numberic' => '203',
                    ],
                    [
                        'name'              => 'Germany',
                        'code_iso_a2'       => 'DE',
                        'code_iso_a3'       => 'DEU',
                        'code_iso_numberic' => '276',
                    ],
                    [
                        'name'              => 'Denmark',
                        'code_iso_a2'       => 'DK',
                        'code_iso_a3'       => 'DNK',
                        'code_iso_numberic' => '208',
                    ],
                    [
                        'name'              => 'Estonia',
                        'code_iso_a2'       => 'EE',
                        'code_iso_a3'       => 'EST',
                        'code_iso_numberic' => '233',
                    ],
                    [
                        'name'              => 'Spain',
                        'code_iso_a2'       => 'ES',
                        'code_iso_a3'       => 'ESP',
                        'code_iso_numberic' => '724',
                    ],
                    [
                        'name'              => 'Finland',
                        'code_iso_a2'       => 'FI',
                        'code_iso_a3'       => 'FIN',
                        'code_iso_numberic' => '246',
                    ],
                    [
                        'name'              => 'Faroe Islands',
                        'code_iso_a2'       => 'FO',
                        'code_iso_a3'       => 'FRO',
                        'code_iso_numberic' => '234',
                    ],
                    [
                        'name'              => 'France',
                        'code_iso_a2'       => 'FR',
                        'code_iso_a3'       => 'FRA',
                        'code_iso_numberic' => '250',
                    ],
                    [
                        'name'              => 'United Kingdom',
                        'code_iso_a2'       => 'GB',
                        'code_iso_a3'       => 'GBR',
                        'code_iso_numberic' => '826',
                    ],
                    [
                        'name'              => 'Guernsey',
                        'code_iso_a2'       => 'GG',
                        'code_iso_a3'       => 'GGY',
                        'code_iso_numberic' => '831',
                    ],
                    [
                        'name'              => 'Gibraltar',
                        'code_iso_a2'       => 'GI',
                        'code_iso_a3'       => 'GIB',
                        'code_iso_numberic' => '292',
                    ],
                    [
                        'name'              => 'Greece',
                        'code_iso_a2'       => 'GR',
                        'code_iso_a3'       => 'GRC',
                        'code_iso_numberic' => '300',
                    ],
                    [
                        'name'              => 'Croatia',
                        'code_iso_a2'       => 'HR',
                        'code_iso_a3'       => 'HRV',
                        'code_iso_numberic' => '191',
                    ],
                    [
                        'name'              => 'Hungary',
                        'code_iso_a2'       => 'HU',
                        'code_iso_a3'       => 'HUN',
                        'code_iso_numberic' => '348',
                    ],
                    [
                        'name'              => 'Ireland',
                        'code_iso_a2'       => 'IE',
                        'code_iso_a3'       => 'IRL',
                        'code_iso_numberic' => '372',
                    ],
                    [
                        'name'              => 'Isle of Man',
                        'code_iso_a2'       => 'IM',
                        'code_iso_a3'       => 'IMN',
                        'code_iso_numberic' => '833',
                    ],
                    [
                        'name'              => 'Iceland',
                        'code_iso_a2'       => 'IS',
                        'code_iso_a3'       => 'ISL',
                        'code_iso_numberic' => '352',
                    ],
                    [
                        'name'              => 'Italy',
                        'code_iso_a2'       => 'IT',
                        'code_iso_a3'       => 'ITA',
                        'code_iso_numberic' => '380',
                    ],
                    [
                        'name'              => 'Jersey',
                        'code_iso_a2'       => 'JE',
                        'code_iso_a3'       => 'JEY',
                        'code_iso_numberic' => '832',
                    ],
                    [
                        'name'              => 'Liechtenstein',
                        'code_iso_a2'       => 'LI',
                        'code_iso_a3'       => 'LIE',
                        'code_iso_numberic' => '438',
                    ],
                    [
                        'name'              => 'Lithuania',
                        'code_iso_a2'       => 'LT',
                        'code_iso_a3'       => 'LTU',
                        'code_iso_numberic' => '440',
                    ],
                    [
                        'name'              => 'Luxembourg',
                        'code_iso_a2'       => 'LU',
                        'code_iso_a3'       => 'LUX',
                        'code_iso_numberic' => '442',
                    ],
                    [
                        'name'              => 'Latvia',
                        'code_iso_a2'       => 'LV',
                        'code_iso_a3'       => 'LVA',
                        'code_iso_numberic' => '428',
                    ],
                    [
                        'name'              => 'Monaco',
                        'code_iso_a2'       => 'MC',
                        'code_iso_a3'       => 'MCO',
                        'code_iso_numberic' => '492',
                    ],
                    [
                        'name'              => 'Moldova',
                        'code_iso_a2'       => 'MD',
                        'code_iso_a3'       => 'MDA',
                        'code_iso_numberic' => '498',
                    ],
                    [
                        'name'              => 'Montenegro',
                        'code_iso_a2'       => 'ME',
                        'code_iso_a3'       => 'MNE',
                        'code_iso_numberic' => '499',
                    ],
                    [
                        'name'              => 'Macedonia',
                        'code_iso_a2'       => 'MK',
                        'code_iso_a3'       => 'MKD',
                        'code_iso_numberic' => '807',
                    ],
                    [
                        'name'              => 'Malta',
                        'code_iso_a2'       => 'MT',
                        'code_iso_a3'       => 'MLT',
                        'code_iso_numberic' => '470',
                    ],
                    [
                        'name'              => 'Netherlands',
                        'code_iso_a2'       => 'NL',
                        'code_iso_a3'       => 'NLD',
                        'code_iso_numberic' => '528',
                    ],
                    [
                        'name'              => 'Norway',
                        'code_iso_a2'       => 'NO',
                        'code_iso_a3'       => 'NOR',
                        'code_iso_numberic' => '578',
                    ],
                    [
                        'name'              => 'Poland',
                        'code_iso_a2'       => 'PL',
                        'code_iso_a3'       => 'POL',
                        'code_iso_numberic' => '616',
                    ],
                    [
                        'name'              => 'Portugal',
                        'code_iso_a2'       => 'PT',
                        'code_iso_a3'       => 'PRT',
                        'code_iso_numberic' => '620',
                    ],
                    [
                        'name'              => 'Romania',
                        'code_iso_a2'       => 'RO',
                        'code_iso_a3'       => 'ROU',
                        'code_iso_numberic' => '642',
                    ],
                    [
                        'name'              => 'Serbia',
                        'code_iso_a2'       => 'RS',
                        'code_iso_a3'       => 'SRB',
                        'code_iso_numberic' => '688',
                    ],
                    [
                        'name'              => 'Russian Federation',
                        'code_iso_a2'       => 'RU',
                        'code_iso_a3'       => 'RUS',
                        'code_iso_numberic' => '643',
                    ],
                    [
                        'name'              => 'Sweden',
                        'code_iso_a2'       => 'SE',
                        'code_iso_a3'       => 'SWE',
                        'code_iso_numberic' => '752',
                    ],
                    [
                        'name'              => 'Slovenia',
                        'code_iso_a2'       => 'SI',
                        'code_iso_a3'       => 'SVN',
                        'code_iso_numberic' => '705',
                    ],
                    [
                        'name'              => 'Svalbard and Jan Mayen Islands',
                        'code_iso_a2'       => 'SJ',
                        'code_iso_a3'       => 'SJM',
                        'code_iso_numberic' => '744',
                    ],
                    [
                        'name'              => 'Slovakia',
                        'code_iso_a2'       => 'SK',
                        'code_iso_a3'       => 'SVK',
                        'code_iso_numberic' => '703',
                    ],
                    [
                        'name'              => 'San Marino',
                        'code_iso_a2'       => 'SM',
                        'code_iso_a3'       => 'SMR',
                        'code_iso_numberic' => '674',
                    ],
                    [
                        'name'              => 'Ukraine',
                        'code_iso_a2'       => 'UA',
                        'code_iso_a3'       => 'UKR',
                        'code_iso_numberic' => '804',
                    ],
                    [
                        'name'              => 'Vatican City',
                        'code_iso_a2'       => 'VA',
                        'code_iso_a3'       => 'VAT',
                        'code_iso_numberic' => '336',
                    ],
                ],
            ],
            'NA' => [
                'name'      => 'North America',
                'code'      => 'NA',
                'countries' => [
                    [
                        'name'              => 'Antigua and Barbuda',
                        'code_iso_a2'       => 'AG',
                        'code_iso_a3'       => 'ATG',
                        'code_iso_numberic' => '028',
                    ],
                    [
                        'name'              => 'Anguilla',
                        'code_iso_a2'       => 'AI',
                        'code_iso_a3'       => 'AIA',
                        'code_iso_numberic' => '660',
                    ],
                    [
                        'name'              => 'Netherlands Antilles',
                        'code_iso_a2'       => 'AN',
                        'code_iso_a3'       => 'ANT',
                        'code_iso_numberic' => '530',
                    ],
                    [
                        'name'              => 'Aruba',
                        'code_iso_a2'       => 'AW',
                        'code_iso_a3'       => 'ABW',
                        'code_iso_numberic' => '533',
                    ],
                    [
                        'name'              => 'Barbados',
                        'code_iso_a2'       => 'BB',
                        'code_iso_a3'       => 'BRB',
                        'code_iso_numberic' => '052',
                    ],
                    [
                        'name'              => 'Saint Barthélemy',
                        'code_iso_a2'       => 'BL',
                        'code_iso_a3'       => 'BLM',
                        'code_iso_numberic' => '652',
                    ],
                    [
                        'name'              => 'Bermuda',
                        'code_iso_a2'       => 'BM',
                        'code_iso_a3'       => 'BMU',
                        'code_iso_numberic' => '060',
                    ],
                    [
                        'name'              => 'Bahamas',
                        'code_iso_a2'       => 'BS',
                        'code_iso_a3'       => 'BHS',
                        'code_iso_numberic' => '044',
                    ],
                    [
                        'name'              => 'Belize',
                        'code_iso_a2'       => 'BZ',
                        'code_iso_a3'       => 'BLZ',
                        'code_iso_numberic' => '084',
                    ],
                    [
                        'name'              => 'Canada',
                        'code_iso_a2'       => 'CA',
                        'code_iso_a3'       => 'CAN',
                        'code_iso_numberic' => '124',
                    ],
                    [
                        'name'              => 'Costa Rica',
                        'code_iso_a2'       => 'CR',
                        'code_iso_a3'       => 'CRI',
                        'code_iso_numberic' => '188',
                    ],
                    [
                        'name'              => 'Cuba',
                        'code_iso_a2'       => 'CU',
                        'code_iso_a3'       => 'CUB',
                        'code_iso_numberic' => '192',
                    ],
                    [
                        'name'              => 'Dominica',
                        'code_iso_a2'       => 'DM',
                        'code_iso_a3'       => 'DMA',
                        'code_iso_numberic' => '212',
                    ],
                    [
                        'name'              => 'Dominican Republic',
                        'code_iso_a2'       => 'DO',
                        'code_iso_a3'       => 'DOM',
                        'code_iso_numberic' => '214',
                    ],
                    [
                        'name'              => 'Grenada',
                        'code_iso_a2'       => 'GD',
                        'code_iso_a3'       => 'GRD',
                        'code_iso_numberic' => '308',
                    ],
                    [
                        'name'              => 'Greenland',
                        'code_iso_a2'       => 'GL',
                        'code_iso_a3'       => 'GRL',
                        'code_iso_numberic' => '304',
                    ],
                    [
                        'name'              => 'Guadeloupe',
                        'code_iso_a2'       => 'GP',
                        'code_iso_a3'       => 'GLP',
                        'code_iso_numberic' => '312',
                    ],
                    [
                        'name'              => 'Guatemala',
                        'code_iso_a2'       => 'GT',
                        'code_iso_a3'       => 'GTM',
                        'code_iso_numberic' => '320',
                    ],
                    [
                        'name'              => 'Honduras',
                        'code_iso_a2'       => 'HN',
                        'code_iso_a3'       => 'HND',
                        'code_iso_numberic' => '340',
                    ],
                    [
                        'name'              => 'Haiti',
                        'code_iso_a2'       => 'HT',
                        'code_iso_a3'       => 'HTI',
                        'code_iso_numberic' => '332',
                    ],
                    [
                        'name'              => 'Jamaica',
                        'code_iso_a2'       => 'JM',
                        'code_iso_a3'       => 'JAM',
                        'code_iso_numberic' => '388',
                    ],
                    [
                        'name'              => 'Saint Kitts and Nevis',
                        'code_iso_a2'       => 'KN',
                        'code_iso_a3'       => 'KNA',
                        'code_iso_numberic' => '659',
                    ],
                    [
                        'name'              => 'Cayman Islands',
                        'code_iso_a2'       => 'KY',
                        'code_iso_a3'       => 'CYM',
                        'code_iso_numberic' => '136',
                    ],
                    [
                        'name'              => 'Saint Lucia',
                        'code_iso_a2'       => 'LC',
                        'code_iso_a3'       => 'LCA',
                        'code_iso_numberic' => '662',
                    ],
                    [
                        'name'              => 'Saint Martin (French part)',
                        'code_iso_a2'       => 'MF',
                        'code_iso_a3'       => 'MAF',
                        'code_iso_numberic' => '663',
                    ],
                    [
                        'name'              => 'Martinique',
                        'code_iso_a2'       => 'MQ',
                        'code_iso_a3'       => 'MTQ',
                        'code_iso_numberic' => '474',
                    ],
                    [
                        'name'              => 'Montserrat',
                        'code_iso_a2'       => 'MS',
                        'code_iso_a3'       => 'MSR',
                        'code_iso_numberic' => '500',
                    ],
                    [
                        'name'              => 'Mexico',
                        'code_iso_a2'       => 'MX',
                        'code_iso_a3'       => 'MEX',
                        'code_iso_numberic' => '484',
                    ],
                    [
                        'name'              => 'Nicaragua',
                        'code_iso_a2'       => 'NI',
                        'code_iso_a3'       => 'NIC',
                        'code_iso_numberic' => '558',
                    ],
                    [
                        'name'              => 'Panama',
                        'code_iso_a2'       => 'PA',
                        'code_iso_a3'       => 'PAN',
                        'code_iso_numberic' => '591',
                    ],
                    [
                        'name'              => 'Saint Pierre and Miquelon',
                        'code_iso_a2'       => 'PM',
                        'code_iso_a3'       => 'SPM',
                        'code_iso_numberic' => '666',
                    ],
                    [
                        'name'              => 'Puerto Rico',
                        'code_iso_a2'       => 'PR',
                        'code_iso_a3'       => 'PRI',
                        'code_iso_numberic' => '630',
                    ],
                    [
                        'name'              => 'El Salvador',
                        'code_iso_a2'       => 'SV',
                        'code_iso_a3'       => 'SLV',
                        'code_iso_numberic' => '222',
                    ],
                    [
                        'name'              => 'Turks and Caicos Islands',
                        'code_iso_a2'       => 'TC',
                        'code_iso_a3'       => 'TCA',
                        'code_iso_numberic' => '796',
                    ],
                    [
                        'name'              => 'Trinidad and Tobago',
                        'code_iso_a2'       => 'TT',
                        'code_iso_a3'       => 'TTO',
                        'code_iso_numberic' => '780',
                    ],
                    [
                        'name'              => 'United States of America',
                        'code_iso_a2'       => 'US',
                        'code_iso_a3'       => 'USA',
                        'code_iso_numberic' => '840',
                    ],
                    [
                        'name'              => 'Saint Vincent and the Grenadines',
                        'code_iso_a2'       => 'VC',
                        'code_iso_a3'       => 'VCT',
                        'code_iso_numberic' => '670',
                    ],
                    [
                        'name'              => 'Virgin Islands, British',
                        'code_iso_a2'       => 'VG',
                        'code_iso_a3'       => 'VGB',
                        'code_iso_numberic' => '092',
                    ],
                    [
                        'name'              => 'Virgin Islands, U.S.',
                        'code_iso_a2'       => 'VI',
                        'code_iso_a3'       => 'VIR',
                        'code_iso_numberic' => '850',
                    ],
                ],
            ],
            'OC' => [
                'name'      => 'Oceania',
                'code'      => 'OC',
                'countries' => [
                    [
                        'name'              => 'American Samoa',
                        'code_iso_a2'       => 'AS',
                        'code_iso_a3'       => 'ASM',
                        'code_iso_numberic' => '016',
                    ],
                    [
                        'name'              => 'Australia',
                        'code_iso_a2'       => 'AU',
                        'code_iso_a3'       => 'AUS',
                        'code_iso_numberic' => '036',
                    ],
                    [
                        'name'              => 'Cook Islands',
                        'code_iso_a2'       => 'CK',
                        'code_iso_a3'       => 'COK',
                        'code_iso_numberic' => '184',
                    ],
                    [
                        'name'              => 'Fiji',
                        'code_iso_a2'       => 'FJ',
                        'code_iso_a3'       => 'FJI',
                        'code_iso_numberic' => '242',
                    ],
                    [
                        'name'              => 'Micronesia',
                        'code_iso_a2'       => 'FM',
                        'code_iso_a3'       => 'FSM',
                        'code_iso_numberic' => '583',
                    ],
                    [
                        'name'              => 'Guam',
                        'code_iso_a2'       => 'GU',
                        'code_iso_a3'       => 'GUM',
                        'code_iso_numberic' => '316',
                    ],
                    [
                        'name'              => 'Kiribati',
                        'code_iso_a2'       => 'KI',
                        'code_iso_a3'       => 'KIR',
                        'code_iso_numberic' => '296',
                    ],
                    [
                        'name'              => 'Marshall Islands',
                        'code_iso_a2'       => 'MH',
                        'code_iso_a3'       => 'MHL',
                        'code_iso_numberic' => '584',
                    ],
                    [
                        'name'              => 'Northern Mariana Islands',
                        'code_iso_a2'       => 'MP',
                        'code_iso_a3'       => 'MNP',
                        'code_iso_numberic' => '580',
                    ],
                    [
                        'name'              => 'New Caledonia',
                        'code_iso_a2'       => 'NC',
                        'code_iso_a3'       => 'NCL',
                        'code_iso_numberic' => '540',
                    ],
                    [
                        'name'              => 'Norfolk Island',
                        'code_iso_a2'       => 'NF',
                        'code_iso_a3'       => 'NFK',
                        'code_iso_numberic' => '574',
                    ],
                    [
                        'name'              => 'Nauru',
                        'code_iso_a2'       => 'NR',
                        'code_iso_a3'       => 'NRU',
                        'code_iso_numberic' => '520',
                    ],
                    [
                        'name'              => 'Niue',
                        'code_iso_a2'       => 'NU',
                        'code_iso_a3'       => 'NIU',
                        'code_iso_numberic' => '570',
                    ],
                    [
                        'name'              => 'New Zealand',
                        'code_iso_a2'       => 'NZ',
                        'code_iso_a3'       => 'NZL',
                        'code_iso_numberic' => '554',
                    ],
                    [
                        'name'              => 'French Polynesia',
                        'code_iso_a2'       => 'PF',
                        'code_iso_a3'       => 'PYF',
                        'code_iso_numberic' => '258',
                    ],
                    [
                        'name'              => 'Papua New Guinea',
                        'code_iso_a2'       => 'PG',
                        'code_iso_a3'       => 'PNG',
                        'code_iso_numberic' => '598',
                    ],
                    [
                        'name'              => 'Pitcairn',
                        'code_iso_a2'       => 'PN',
                        'code_iso_a3'       => 'PCN',
                        'code_iso_numberic' => '612',
                    ],
                    [
                        'name'              => 'Palau',
                        'code_iso_a2'       => 'PW',
                        'code_iso_a3'       => 'PLW',
                        'code_iso_numberic' => '585',
                    ],
                    [
                        'name'              => 'Solomon Islands',
                        'code_iso_a2'       => 'SB',
                        'code_iso_a3'       => 'SLB',
                        'code_iso_numberic' => '090',
                    ],
                    [
                        'name'              => 'Tokelau',
                        'code_iso_a2'       => 'TK',
                        'code_iso_a3'       => 'TKL',
                        'code_iso_numberic' => '772',
                    ],
                    [
                        'name'              => 'Tonga',
                        'code_iso_a2'       => 'TO',
                        'code_iso_a3'       => 'TON',
                        'code_iso_numberic' => '776',
                    ],
                    [
                        'name'              => 'Tuvalu',
                        'code_iso_a2'       => 'TV',
                        'code_iso_a3'       => 'TUV',
                        'code_iso_numberic' => '798',
                    ],
                    [
                        'name'              => 'United States Minor Outlying Islands',
                        'code_iso_a2'       => 'UM',
                        'code_iso_a3'       => 'UMI',
                        'code_iso_numberic' => '581',
                    ],
                    [
                        'name'              => 'Vanuatu',
                        'code_iso_a2'       => 'VU',
                        'code_iso_a3'       => 'VUT',
                        'code_iso_numberic' => '548',
                    ],
                    [
                        'name'              => 'Wallis and Futuna Islands',
                        'code_iso_a2'       => 'WF',
                        'code_iso_a3'       => 'WLF',
                        'code_iso_numberic' => '876',
                    ],
                    [
                        'name'              => 'Samoa',
                        'code_iso_a2'       => 'WS',
                        'code_iso_a3'       => 'WSM',
                        'code_iso_numberic' => '882',
                    ],
                ],
            ],
            'SA' => [
                'name'      => 'South America',
                'code'      => 'SA',
                'countries' => [
                    [
                        'name'              => 'Argentina',
                        'code_iso_a2'       => 'AR',
                        'code_iso_a3'       => 'ARG',
                        'code_iso_numberic' => '032',
                    ],
                    [
                        'name'              => 'Bolivia',
                        'code_iso_a2'       => 'BO',
                        'code_iso_a3'       => 'BOL',
                        'code_iso_numberic' => '068',
                    ],
                    [
                        'name'              => 'Brazil',
                        'code_iso_a2'       => 'BR',
                        'code_iso_a3'       => 'BRA',
                        'code_iso_numberic' => '076',
                    ],
                    [
                        'name'              => 'Chile',
                        'code_iso_a2'       => 'CL',
                        'code_iso_a3'       => 'CHL',
                        'code_iso_numberic' => '152',
                    ],
                    [
                        'name'              => 'Colombia',
                        'code_iso_a2'       => 'CO',
                        'code_iso_a3'       => 'COL',
                        'code_iso_numberic' => '170',
                    ],
                    [
                        'name'              => 'Ecuador',
                        'code_iso_a2'       => 'EC',
                        'code_iso_a3'       => 'ECU',
                        'code_iso_numberic' => '218',
                    ],
                    [
                        'name'              => 'Falkland Islands',
                        'code_iso_a2'       => 'FK',
                        'code_iso_a3'       => 'FLK',
                        'code_iso_numberic' => '238',
                    ],
                    [
                        'name'              => 'French Guiana',
                        'code_iso_a2'       => 'GF',
                        'code_iso_a3'       => 'GUF',
                        'code_iso_numberic' => '254',
                    ],
                    [
                        'name'              => 'Guyana',
                        'code_iso_a2'       => 'GY',
                        'code_iso_a3'       => 'GUY',
                        'code_iso_numberic' => '328',
                    ],
                    [
                        'name'              => 'Peru',
                        'code_iso_a2'       => 'PE',
                        'code_iso_a3'       => 'PER',
                        'code_iso_numberic' => '604',
                    ],
                    [
                        'name'              => 'Paraguay',
                        'code_iso_a2'       => 'PY',
                        'code_iso_a3'       => 'PRY',
                        'code_iso_numberic' => '600',
                    ],
                    [
                        'name'              => 'Suriname',
                        'code_iso_a2'       => 'SR',
                        'code_iso_a3'       => 'SUR',
                        'code_iso_numberic' => '740',
                    ],
                    [
                        'name'              => 'Uruguay',
                        'code_iso_a2'       => 'UY',
                        'code_iso_a3'       => 'URY',
                        'code_iso_numberic' => '858',
                    ],
                    [
                        'name'              => 'Venezuela',
                        'code_iso_a2'       => 'VE',
                        'code_iso_a3'       => 'VEN',
                        'code_iso_numberic' => '862',
                    ],
                ],
            ],
        ];

        foreach ($data as $item) {
            $continent       = new Continent;
            $continent->name = $item['name'];
            $continent->code = $item['code'];
            $continent->save();

            foreach ($item['countries'] as $c) {
                $country                    = new Country;
                $country->continent_id      = $continent->id;
                $country->name              = $c['name'];
                $country->code_iso_a2       = $c['code_iso_a2'];
                $country->code_iso_a3       = $c['code_iso_a3'];
                $country->code_iso_numberic = $c['code_iso_numberic'];
                $country->save();
            }
        }

    }
}
